flutter-tizen/embedder

flutter/shell/platform/tizen/BUILD.gn
flutter/shell/platform/tizen/flutter_tizen.cc
flutter/shell/platform/tizen/public/flutter_tizen.h
flutter/shell/platform/tizen/tizen_window_elementary.cc
flutter/shell/platform/tizen/tizen_window_elementary.h
tools/generate_sysroot.py

Add feature to support external output in common profile.
The eom API only supports elm_win. So TizenWindowElementary supports this.
Currently, only HDMI type is available.
It can be extended according to the requirements of the Common profile.
https://docs.tizen.org/application/native/guides/device/ext-output/
+)
How to map input device.
1) Check to input event node.
$) winfo -input_devices
2) Set to input and output event node 
$) winfo -input_output_set [input(ex./dev/input/eventX)] [output(ex.HDMIA-1)]
related pr : https://github.com/flutter-tizen/flutter-tizen/pull/465

Add external output support

---

.github/workflows/build.yml
tools/check_symbols.py

The ubuntu-latest image now maps to ubuntu-22.04 on GitHub Actions. Ignore the symbol version part of the `nm` output.
https://github.com/flutter-tizen/embedder/actions/runs/3528676880

[ci] Fix check-symbols failing on ubuntu-latest

---

flutter/shell/platform/tizen/tizen_renderer_egl.cc

Previously, there was a problem using Dali::AnyCast() due to libcxx issues.
The embedder has been migrated not to use flutter's libcxx(use_flutter_cxx option)
Therefore, there is no need to directly access the implementation of container of Dali::Any.
So it changed to cast to tbm_surface_queue_h using Dali::AnyCast().

TizenRendererEgl: Use AnyCast() to cast to tbm_surface_queue

---

flutter/shell/platform/tizen/BUILD.gn
flutter/shell/platform/tizen/channels/app_control.cc
flutter/shell/platform/tizen/channels/platform_channel.cc
flutter/shell/platform/tizen/channels/platform_channel.h
flutter/shell/platform/tizen/channels/window_channel.h

Use the platform clipboard API (CBHM) to implement a text clipboard that supports app-to-app copy-and-paste (including non-Flutter apps). The API is only available for mobile and common profiles, so other profiles will continue to use the old naive implementation that comes with limited functionality.
See also: https://github.com/flutter-tizen/engine/pull/65 (the original implementation by @pkosko)

Improve the clipboard implementation

---

flutter/shell/platform/tizen/channels/platform_channel.cc
flutter/shell/platform/tizen/flutter_tizen.cc
flutter/shell/platform/tizen/flutter_tizen_view.cc
flutter/shell/platform/tizen/tizen_view.h
flutter/shell/platform/tizen/tizen_view_base.h
flutter/shell/platform/tizen/tizen_window.h

The embedder does not require a type for the class because -rtti option is enabled.
So, remove the type enum and the getter method.

TizenViewBase: Remove TizenViewType enum and GetType()

---

flutter/shell/platform/tizen/BUILD.gn
flutter/shell/platform/tizen/flutter_tizen.cc
flutter/shell/platform/tizen/flutter_tizen_engine.cc
flutter/shell/platform/tizen/flutter_tizen_texture_registrar.cc
flutter/shell/platform/tizen/flutter_tizen_view.cc
flutter/shell/platform/tizen/tizen_renderer.h
flutter/shell/platform/tizen/tizen_renderer_egl.cc
flutter/shell/platform/tizen/tizen_renderer_evas_gl.cc

The embedder does not require a type getter of renderer because -rtti option is enabled.
So, remove getter method.

TizenRenderer: Remove renderer type getter

---

DEPS

The ninja binary is being removed from depot_tools.
https://bugs.chromium.org/p/chromium/issues/detail?id=1340825
Fixes the following error.
```sh
depot_tools/ninja.py: Could not find Ninja in the third_party of the current project, nor in your PATH.
Please take a following action to install Ninja.
- If your project has DEPS, Add a CIPD Ninja dependency to DEPS.
- Oterweise, Add Ninja to your PATH *after* depot_tools.
Error: Process completed with exit code 1.
```

[tools] Install CIPD ninja using DEPS

---

flutter/shell/platform/common/BUILD.gn
flutter/shell/platform/common/client_wrapper/core_implementations.cc
flutter/shell/platform/common/client_wrapper/include/flutter/event_channel.h
flutter/shell/platform/common/client_wrapper/include/flutter/texture_registrar.h
flutter/shell/platform/common/client_wrapper/texture_registrar_impl.h
flutter/shell/platform/common/incoming_message_dispatcher.cc
flutter/shell/platform/common/public/flutter_export.h
flutter/shell/platform/common/public/flutter_macros.h
flutter/shell/platform/common/public/flutter_messenger.h
flutter/shell/platform/common/public/flutter_texture_registrar.h
flutter/shell/platform/common/text_editing_delta.cc
flutter/shell/platform/common/text_editing_delta.h
flutter/shell/platform/embedder/embedder.h
flutter/shell/platform/tizen/flutter_tizen.cc

Copy common headers and source code (including `embedder.h` and cpp_client_wrapper) from the Flutter 3.7 engine source tree except accessibility-related code.
TODO:
- There will be a follow-up PR soon.
- Refer to https://github.com/flutter/engine/pull/36909/files.
- We don't currently have a plan to implement this. Let's revisit when it becomes necessary.
- Refer to https://github.com/flutter/engine/pull/37404/files.

[engine] Sync Flutter 3.7 source code

---

flutter/shell/platform/tizen/flutter_tizen_engine.cc
flutter/shell/platform/tizen/flutter_tizen_engine.h

Align the Tizen embedder with the new `update_semantics_callback` embedder API.
For details, please see https://github.com/flutter/engine/pull/37404. I referred to Windows and macOS implementations.

[a11y] Move to new update semantics API

---

flutter/shell/platform/tizen/accessibility_settings.cc
flutter/shell/platform/tizen/channels/app_control.cc
flutter/shell/platform/tizen/channels/key_event_channel.cc
flutter/shell/platform/tizen/channels/settings_channel.cc
flutter/shell/platform/tizen/flutter_tizen.cc
flutter/shell/platform/tizen/flutter_tizen_engine.cc
flutter/shell/platform/tizen/tizen_event_loop.cc
flutter/shell/platform/tizen/tizen_input_method_context.cc
flutter/shell/platform/tizen/tizen_view_elementary.cc
flutter/shell/platform/tizen/tizen_vsync_waiter.cc
flutter/shell/platform/tizen/tizen_window_ecore_wl2.cc
flutter/shell/platform/tizen/tizen_window_elementary.cc

Variables whose types can be known at compile time should be converted using `static_cast`.

Minimize use of reinterpret_cast

---

flutter/shell/platform/tizen/BUILD.gn
flutter/shell/platform/tizen/flutter_tizen.cc
flutter/shell/platform/tizen/flutter_tizen_view.cc
flutter/shell/platform/tizen/flutter_tizen_view.h
flutter/shell/platform/tizen/tizen_view_elementary.cc
flutter/shell/platform/tizen/tizen_view_event_handler_delegate.h
flutter/shell/platform/tizen/tizen_window_ecore_wl2.cc
flutter/shell/platform/tizen/tizen_window_elementary.cc

Contributes to https://github.com/flutter-tizen/flutter-tizen/issues/490.
- Specify `FlutterPointerEvent.device_kind` according to the actual device type.
- Handle multi device states correctly.
- Handle mouse hover events and right and middle click events correctly.
- Fix `Evas_Event_Mouse_Down.button` being incorrectly used as a device ID and use `mouse_event->dev` instead.
- Update `kScrollOffsetMultiplier` with the value used by Chromium/Linux GTK.
The code added to `flutter_tizen_view.cc` is mostly based on the Windows implementation (`flutter_windows_view.cc`).
To test right and middle clicks, you can use the `GestureDetector` widget (`onSecondaryTapDown`/`onTertiaryTapDown`).

Handle right and middle mouse button clicks

---

flutter/shell/platform/tizen/external_texture_surface_egl.cc
flutter/shell/platform/tizen/external_texture_surface_evas_gl.cc

std::unique_ptr::release, just releases the ownership of the managed object, the caller is responsible for deleting the object.

Fix memory leak issue

---

flutter/shell/platform/common/client_wrapper/include/flutter/event_channel.h
flutter/shell/platform/common/client_wrapper/include/flutter/event_stream_handler.h
flutter/shell/platform/common/client_wrapper/include/flutter/method_channel.h
flutter/shell/platform/common/client_wrapper/standard_codec.cc
flutter/shell/platform/embedder/embedder.h

Copy `embedder.h` and `client_wrapper` from the Flutter 3.10 engine source tree.

[engine] Sync Flutter 3.10 source code

---

.github/workflows/analyze.yml
.github/workflows/build.yml
README.md
tools/download_engine.py

Somehow I can't install `requests` on my PC.
`urllib` is a bit slower but it shouldn't matter too much.

[tools] Remove requests dependency

---

DEPS
README.md
build/config/BUILD.gn
build/config/BUILDCONFIG.gn
build/secondary/third_party/libcxx/BUILD.gn
build/secondary/third_party/libcxx/config/__config_site
build/secondary/third_party/libcxxabi/BUILD.gn
flutter/shell/platform/tizen/channels/key_event_channel.cc
flutter/shell/platform/tizen/flutter_tizen_engine.cc
flutter/shell/platform/tizen/tizen_window_ecore_wl2.cc
flutter/third_party/accessibility/ax/ax_event_generator.h

- Align libcxx, libcxxabi, dart-sdk, clang, and ninja versions with Flutter 3.10.
- Compile libcxx using C++20. See https://github.com/flutter/buildroot/commit/633907dfb90f6e8d97ad122aa66cf2d4207cda9b for details.
- Resolve deprecation warnings.
- Format the source code with the updated clang-format (clang-format-16).

Update libcxx and other dependencies

---

flutter/shell/platform/tizen/channels/app_control.h
flutter/shell/platform/tizen/channels/app_control_channel.cc
flutter/shell/platform/tizen/channels/encodable_value_holder.h

Add the `getHandle` method to support a feature requested by an internal developer.
cc @haesik @hjhun @bbrto21

Add getHandle method to the app control channel

---

flutter/shell/platform/tizen/flutter_tizen_engine.cc
flutter/shell/platform/tizen/flutter_tizen_engine.h

Need check whether vsync_waiter_ is a null pointer, because during stop engine process, may receive a request for vsync.

Fix coredump issue during exit app

---

flutter/shell/platform/tizen/channels/platform_channel.cc

LiveText.isLiveTextInputAvailable is a method not supported in Tizen.

Add LiveText.isLiveTextInputAvailable to unsupported method

---

.github/workflows/build.yml

clang 12 has been removed from ubuntu-latest(22.04).
https://github.com/actions/runner-images/issues/8263

[ci] Add clang-12 to build dependencies

---

flutter/shell/platform/tizen/BUILD.gn
flutter/shell/platform/tizen/channels/input_device_channel.cc
flutter/shell/platform/tizen/channels/input_device_channel.h
flutter/shell/platform/tizen/flutter_tizen.cc
flutter/shell/platform/tizen/flutter_tizen_view.cc
flutter/shell/platform/tizen/flutter_tizen_view.h
flutter/shell/platform/tizen/tizen_view_elementary.cc
flutter/shell/platform/tizen/tizen_view_event_handler_delegate.h
flutter/shell/platform/tizen/tizen_view_nui.cc
flutter/shell/platform/tizen/tizen_window_ecore_wl2.cc
flutter/shell/platform/tizen/tizen_window_elementary.cc

This is a feature requested by our customer (3rd-party TV app developer).
To retrieve the name of the last keyboard device used:
```dart
final device = await MethodChannel('tizen/internal/inputdevice')
.invokeMapMethod<String, dynamic>('getLastUsedKeyboard');
final name = device!['name'] as String;
```
For TV remote controls, the result is either of the following.
- IR remote control: `wt61p807 rc device`
- Smart remote control (bluetooth): `Smart Control [year]`
- Virtual keyboard: `ime` (updated when closing the keyboard)
- Virtual numpad: `virtual key device` (updated on pressing the Done button on Tizen 6.5 or higher, otherwise updated immediately when pressed numbers)
For example, if the developer wants to detect whether the user used a virtual numpad to enter a number, they can …

Add the input device channel

---

flutter/shell/platform/tizen/flutter_tizen.cc
flutter/shell/platform/tizen/public/flutter_tizen.h
flutter/shell/platform/tizen/tizen_view_base.h
flutter/shell/platform/tizen/tizen_view_elementary.cc
flutter/shell/platform/tizen/tizen_view_elementary.h
flutter/shell/platform/tizen/tizen_view_nui.cc
flutter/shell/platform/tizen/tizen_view_nui.h
flutter/shell/platform/tizen/tizen_window_ecore_wl2.cc
flutter/shell/platform/tizen/tizen_window_ecore_wl2.h
flutter/shell/platform/tizen/tizen_window_elementary.cc
flutter/shell/platform/tizen/tizen_window_elementary.h

Replace surface id with resource id for fixing overlap issue on Tizen TV  6.0.

Implement FlutterDesktopViewGetResourceId

---

flutter/shell/platform/tizen/channels/app_control.h
flutter/shell/platform/tizen/channels/app_control_channel.cc

`AppControlManager` is not thread-safe and may cause the following exception (reported by a third-party developer) when the UI thread (Dart code) is notified of an app control event (by `NotifyAppControl`) and tries to access the associated app control instance through `NativeAttachAppControl` before the instance is added to `AppControlManager` on the platform thread.
```dart
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Exception: Could not find an instance of AppControl with ID 1.
#0      new AppControl._fromMap (package:tizen_app_control/src/app_control.dart:88:7)
#1      new ReceivedAppControl._fromMap (package:tizen_app_control/src/app_control.dart:263:15)
#2      AppControl.onAppControl.<anonymous closure> …
```

Prevent possible race condition in NotifyAppControl

---

flutter/shell/platform/tizen/flutter_tizen.cc
flutter/shell/platform/tizen/flutter_tizen_elementary.cc
flutter/shell/platform/tizen/flutter_tizen_engine.h
flutter/shell/platform/tizen/flutter_tizen_nui.cc
flutter/shell/platform/tizen/flutter_tizen_view.cc
flutter/shell/platform/tizen/flutter_tizen_view.h

This PR adds a new field `view_id` to embedder API's `FlutterPointerEvent`,
allowing platforms to specify the source view of pointer events.

Add view_id for FlutterPointerEvent

---

flutter/shell/platform/tizen/BUILD.gn
flutter/shell/platform/tizen/channels/platform_channel.cc
flutter/shell/platform/tizen/channels/platform_channel.h
tools/generate_sysroot.py

cbhm library has been deprecated in Tizen 8.0.
Therefore, remove cbhm related code.
Copy&paste between applications is not supported for the time being in common and mobile profile.
(Copy&paste within applications is still supported.)
This feature will be supported again using the ecore_wl2 API.

Remove cbhm dependency

---

flutter/shell/platform/tizen/BUILD.gn
flutter/shell/platform/tizen/channels/platform_channel.cc
flutter/shell/platform/tizen/channels/platform_channel.h
flutter/shell/platform/tizen/tizen_clipboard.cc
flutter/shell/platform/tizen/tizen_clipboard.h

Starting from Tizen 8.0, the cbhm package is not distributed.
Therefore, support the platform's clipboard feature using the ecore_wl2 APIs.
ecore_wl2_offer_receive() and ecore_wl2_offer_mimes_get() can be found in Tizen 5.5 rootstrap,
but are not distributed in the actual ecore_wl2 header.
Therefore, this feature is supported starting from tizen 6.5.
This feature supports TV profiles of Tizen 6.5 or higher.
However, in Tizen 6.0 and below, copy&paste is supported only for data within the application.

Improve clipboard without cbhm

---

.github/workflows/build.yml
README.md
build/config/BUILDCONFIG.gn
flutter/shell/platform/tizen/BUILD.gn
flutter/shell/platform/tizen/accessibility_settings.cc
flutter/shell/platform/tizen/flutter_tizen.cc
flutter/shell/platform/tizen/flutter_tizen_engine.cc
flutter/shell/platform/tizen/flutter_tizen_engine.h
flutter/shell/platform/tizen/flutter_tizen_texture_registrar.cc
flutter/shell/platform/tizen/flutter_tizen_view.cc
flutter/shell/platform/tizen/tizen_evas_gl_helper.h
flutter/shell/platform/tizen/tizen_window_elementary.cc
tools/generate_sysroot.py
tools/gn

- Remove Tizen 5.5 support.
- Remove Wearable support.

Change minimum Tizen version 5.5 to 6.0

---

flutter/shell/platform/common/accessibility_bridge.cc
flutter/shell/platform/common/accessibility_bridge.h
flutter/shell/platform/common/client_wrapper/include/flutter/basic_message_channel.h
flutter/shell/platform/common/client_wrapper/include/flutter/event_channel.h
flutter/shell/platform/common/client_wrapper/include/flutter/method_result_functions.h
flutter/shell/platform/common/client_wrapper/include/flutter/plugin_registrar.h
flutter/shell/platform/common/client_wrapper/include/flutter/texture_registrar.h
flutter/shell/platform/common/incoming_message_dispatcher.h
flutter/shell/platform/common/path_utils.h
flutter/shell/platform/common/platform_provided_menu.h
flutter/shell/platform/common/public/flutter_messenger.h
flutter/shell/platform/common/text_input_model.cc
flutter/shell/platform/common/text_input_model.h
flutter/shell/platform/embedder/embedder.h

+) https://github.com/flutter-tizen/engine/tree/flutter-3.22.0

[engine] Sync Flutter 3.22.0 source code

---

flutter/shell/platform/tizen/flutter_tizen_engine.cc
flutter/shell/platform/tizen/tizen_renderer_egl.cc
flutter/shell/platform/tizen/tizen_renderer_egl.h

When there is an impeller argument, set egl config to match the impeller.

Support imepller in egl renderer

---

DEPS
build/secondary/third_party/googletest/BUILD.gn
flutter/shell/platform/embedder/embedder.h

+) https://github.com/flutter/engine/commits/3.24.1

[engine] Sync Flutter 3.24.1 source code

---

flutter/shell/platform/tizen/channels/text_input_channel.cc

If TextInputType is none, the software keyboard will not be shown.
https://api.flutter.dev/flutter/services/TextInputType/none-constant.html
[test code]
```dart
const TextField(
decoration: InputDecoration(
labelText: 'Input',
),
keyboardType: TextInputType.none,
),
```

Support TextInputType.none in TextInputChannel

---

flutter/shell/platform/tizen/channels/accessibility_channel.cc

There is case where a crash occurs because eldbus is not initialized in RPI.
To prevent this, initialization and shutdown are added.

[a11y] Add eldbus initialization

---

.github/workflows/build.yml
README.md
build/config/BUILD.gn
build/config/BUILDCONFIG.gn

ubuntu-latest has been changed to 24.04.
clang-12 is no longer in 24.04 repository.

[ci] Change llvm-12 to llvm-17

---

flutter/shell/platform/tizen/channels/platform_channel.cc
flutter/shell/platform/tizen/tizen_window_ecore_wl2.cc

+) https://github.com/flutter-tizen/embedder/issues/19
+)Set only landscape as default for TV profile.
For [webapps on TV devices](https://developer.samsung.com/smarttv/develop/guides/sero-guide.html), the default orientation setting is landscape only. This keep the output screen to be display to landscape even if the physical device is portrait mode.
To behave according to the device's orientation(like "all" as webapp, the user can call SystemChrome.setPreferredOrientations() from the app to set it.
```
SystemChrome.setPreferredOrientations([
DeviceOrientation.portraitDown,
DeviceOrientation.portraitUp,
DeviceOrientation.landscapeLeft,
DeviceOrientation.landscapeRight,
]);
```

Set rotations properly for landscape default devices

---

flutter/shell/platform/tizen/flutter_tizen.cc
flutter/shell/platform/tizen/flutter_tizen_view.cc
flutter/shell/platform/tizen/flutter_tizen_view.h
flutter/shell/platform/tizen/public/flutter_tizen.h

Previously, we used values calculated through Base scale calculation using DPI and DeviceFactor used in Tizen.
Since it follows Tizen UX, it can show the same look as other apps on TV. (https://docs.tizen.org/application/native/guides/ui/efl/multiple-screens/)
However, when running an app written for another platform on Tizen, the scale may appear different.
So I add user_pixel_ratio to WindowProperty to allow the user to adjust this scale.

Add user-defined pixel ratio

---

flutter/shell/platform/tizen/flutter_tizen.cc
flutter/shell/platform/tizen/public/flutter_tizen.h
flutter/shell/platform/tizen/tizen_window_ecore_wl2.cc
flutter/shell/platform/tizen/tizen_window_ecore_wl2.h

If there is a window handle passed in from embedding, use it.
This window handle is a pre-created window and can get by functions implemented in NUI(Dali).
In elementary windows(elm_win) case, there is no plan.

Using precreated window

---

flutter/third_party/accessibility/ax/platform/ax_platform_node_base.cc

Fix : #91 
Refer to : https://chromium-review.googlesource.com/c/chromium/src/+/4418610

[a11y] AXPlatformNodeBase::GetIndexInParent: Remove BASE_UNREACHABLE

---

flutter/third_party/accessibility/ax/platform/ax_platform_atk_hyperlink.cc
flutter/third_party/accessibility/ax/platform/ax_platform_node_auralinux.cc

The variables here are only marked as volatile because they’re arguments to `g_once_*()`.
Related chromium commit:
https://chromium-review.googlesource.com/c/chromium/src/+/3960017
Related glib commit:
https://github.com/GNOME/glib/commit/fab561f8d0

Drop use of volatile with g_once_*()
